// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArg5wXmdiDBaOn0LFaAsx9nZNTkO4kV_0',
    appId: '1:268266503951:web:8940f690c96f2ada04087a',
    messagingSenderId: '268266503951',
    projectId: 'ecommerce-c1e8a',
    authDomain: 'ecommerce-c1e8a.firebaseapp.com',
    storageBucket: 'ecommerce-c1e8a.firebasestorage.app',
    measurementId: 'G-YSTS2J1C93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtStifgaSVl2KaFrZoVa2jBPw-uzCf6T0',
    appId: '1:268266503951:android:daded5f5487cd46704087a',
    messagingSenderId: '268266503951',
    projectId: 'ecommerce-c1e8a',
    storageBucket: 'ecommerce-c1e8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuENAYJCIaNh7NpzQet2mAhdvFsElcCRQ',
    appId: '1:268266503951:ios:27876ec4c1b47dfa04087a',
    messagingSenderId: '268266503951',
    projectId: 'ecommerce-c1e8a',
    storageBucket: 'ecommerce-c1e8a.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuENAYJCIaNh7NpzQet2mAhdvFsElcCRQ',
    appId: '1:268266503951:ios:27876ec4c1b47dfa04087a',
    messagingSenderId: '268266503951',
    projectId: 'ecommerce-c1e8a',
    storageBucket: 'ecommerce-c1e8a.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArg5wXmdiDBaOn0LFaAsx9nZNTkO4kV_0',
    appId: '1:268266503951:web:ba914832ad55e3cc04087a',
    messagingSenderId: '268266503951',
    projectId: 'ecommerce-c1e8a',
    authDomain: 'ecommerce-c1e8a.firebaseapp.com',
    storageBucket: 'ecommerce-c1e8a.firebasestorage.app',
    measurementId: 'G-0TJ3KC5K79',
  );
}
